//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zieschang.Net.Projects.PostsharpAspects.Aspects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zieschang.Net.Projects.PostsharpAspects.Aspects.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing paremter declaration! Set [ParameterName] or [ParameterIndex] property!.
        /// </summary>
        internal static string JZI001 {
            get {
                return ResourceManager.GetString("JZI001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}.{1}&apos; does not have a parameter with index {2}.
        /// </summary>
        internal static string JZI002 {
            get {
                return ResourceManager.GetString("JZI002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}.{1}&apos; does not have a parameter match name {2}.
        /// </summary>
        internal static string JZI003 {
            get {
                return ResourceManager.GetString("JZI003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}.{1}&apos; does not have a parameter any parameter.
        /// </summary>
        internal static string JZI004 {
            get {
                return ResourceManager.GetString("JZI004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}.{1}&apos; parameter {2} is a value type, which cannot be null!.
        /// </summary>
        internal static string JZI005 {
            get {
                return ResourceManager.GetString("JZI005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryName is required!.
        /// </summary>
        internal static string JZI006 {
            get {
                return ResourceManager.GetString("JZI006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterName is required!.
        /// </summary>
        internal static string JZI007 {
            get {
                return ResourceManager.GetString("JZI007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrapExceptionType must be of type exception!.
        /// </summary>
        internal static string PJZI001 {
            get {
                return ResourceManager.GetString("PJZI001", resourceCulture);
            }
        }
    }
}
